# Generated by Django 4.2 on 2025-10-08 22:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_task_assigned_group_alter_task_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskphoto',
            name='image',
        ),
        migrations.AddField(
            model_name='task',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Подтверждена'),
        ),
        migrations.AddField(
            model_name='taskphoto',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание фото'),
        ),
        migrations.AddField(
            model_name='taskphoto',
            name='photo',
            field=models.ImageField(default='', upload_to='task_photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskphoto',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='tasks.task'),
        ),
        migrations.AlterField(
            model_name='taskphoto',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загружено'),
        ),
    ]
