# Generated by Django 4.2 on 2025-10-09 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_acknowledged_at_task_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='OesObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(db_index=True, unique=True, verbose_name='ID Объекта OES')),
                ('name', models.CharField(max_length=255, verbose_name='Название Объекта')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Сырые данные JSON')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Последнее Обновление')),
            ],
            options={
                'verbose_name': 'Объект OES',
                'verbose_name_plural': 'Объекты OES',
                'ordering': ['name'],
            },
        ),
    ]
