# Generated by Django 4.2 on 2025-10-09 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_oesobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='OesCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(help_text='ID категории из внешнего источника.', unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория OES',
                'verbose_name_plural': 'Категории OES',
            },
        ),
        migrations.AlterModelOptions(
            name='oesobject',
            options={'verbose_name': 'Объект OES', 'verbose_name_plural': 'Объекты OES'},
        ),
        migrations.RemoveField(
            model_name='oesobject',
            name='data',
        ),
        migrations.RemoveField(
            model_name='oesobject',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='oesobject',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='oesobject',
            name='mdm_object_uuid',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='MDM UUID'),
        ),
        migrations.AddField(
            model_name='oesobject',
            name='source_id',
            field=models.IntegerField(help_text='ID объекта из внешнего источника.', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='task',
            name='oes_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.oesobject', verbose_name='Связанный OES Объект'),
        ),
        migrations.AlterField(
            model_name='oesobject',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название объекта'),
        ),
        migrations.CreateModel(
            name='OesObjectDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(help_text='ID устройства из внешнего источника.', null=True, unique=True)),
                ('source_object_id', models.CharField(max_length=255, unique=True, verbose_name='Внешний ID устройства')),
                ('oes_object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='tasks.oesobject', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Устройство OES',
                'verbose_name_plural': 'Устройства OES',
            },
        ),
        migrations.CreateModel(
            name='OesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.IntegerField(help_text='ID модели из внешнего источника.', unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название модели')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='tasks.oescategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Модель OES',
                'verbose_name_plural': 'Модели OES',
            },
        ),
        migrations.AddField(
            model_name='oesobject',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='tasks.oesmodel', verbose_name='Модель'),
        ),
    ]
