# Generated by Django 4.2 on 2025-10-09 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_oescategory_alter_oesobject_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oesobject',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oes_objects', to='tasks.oesmodel', verbose_name='Модель'),
        ),
    ]
