# Generated by Django 4.2 on 2025-10-09 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_oesobject_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='oes_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.oesmodel', verbose_name='Выбранная модель оборудования'),
        ),
    ]
