# Generated by Django 4.2 on 2025-10-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_task_oes_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItilIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(max_length=100, unique=True, verbose_name='ID инцидента')),
                ('document_date', models.DateTimeField(verbose_name='Дата документа')),
                ('document_service', models.CharField(max_length=200, verbose_name='Услуга')),
                ('document_initiator', models.CharField(max_length=200, verbose_name='Инициатор')),
                ('initiator_organization', models.CharField(max_length=200, verbose_name='Организация инициатора')),
                ('document_status', models.CharField(max_length=100, verbose_name='Статус')),
                ('assignment_time', models.DateTimeField(verbose_name='Время назначения ответственного')),
                ('current_executor', models.CharField(max_length=200, verbose_name='Текущий исполнитель')),
                ('current_stage', models.CharField(max_length=200, verbose_name='Текущий этап')),
                ('deadline_exceeded', models.CharField(max_length=50, verbose_name='Превышен срок решения')),
                ('document_route', models.CharField(max_length=200, verbose_name='Маршрут')),
                ('deadline', models.DateTimeField(verbose_name='Крайний срок устранения')),
                ('document_priority', models.CharField(max_length=50, verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
            ],
            options={
                'verbose_name': 'ITIL Инцидент',
                'verbose_name_plural': 'ITIL Инциденты',
                'ordering': ['-document_date'],
            },
        ),
    ]
