# Generated by Django 4.2 on 2025-10-10 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_itilincident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itilincident',
            name='assignment_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время назначения ответственного'),
        ),
        migrations.AlterField(
            model_name='itilincident',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Крайний срок устранения'),
        ),
    ]
