# Generated by Django 4.2 on 2025-10-10 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0011_alter_itilincident_assignment_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='oes_model',
        ),
        migrations.AddField(
            model_name='task',
            name='external_data',
            field=models.JSONField(blank=True, help_text='JSON с дополнительными данными из внешней системы', null=True, verbose_name='Дополнительные данные'),
        ),
        migrations.AddField(
            model_name='task',
            name='external_id',
            field=models.CharField(blank=True, help_text='ID задачи во внешней системе', max_length=100, null=True, verbose_name='Внешний ID'),
        ),
        migrations.AddField(
            model_name='task',
            name='external_source',
            field=models.CharField(blank=True, help_text='Например: ITIL, Jira, etc.', max_length=50, null=True, verbose_name='Внешний источник'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Репортер (Создатель)'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('external_source__isnull', False), ('external_id__isnull', False)), fields=('external_source', 'external_id'), name='unique_external_task'),
        ),
    ]
