# Generated by Django 4.2 on 2025-10-10 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0012_remove_task_oes_model_task_external_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaultCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Категория неисправности',
                'verbose_name_plural': 'Категории неисправностей',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaskCompletionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_performed', models.TextField(verbose_name='Выполненная работа')),
                ('root_cause', models.TextField(blank=True, verbose_name='Корневая причина')),
                ('preventive_measures', models.TextField(blank=True, verbose_name='Предупредительные меры')),
                ('time_spent', models.DurationField(blank=True, null=True, verbose_name='Затраченное время')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания отчета')),
                ('completed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель')),
                ('fault_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.faultcategory', verbose_name='Категория неисправности')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_report', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Отчет о закрытии задачи',
                'verbose_name_plural': 'Отчеты о закрытии задач',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ItilIncident',
        ),
    ]
