# Generated by Django 4.2 on 2025-10-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_faultcategory_taskcompletionreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='itil_number',
            field=models.CharField(blank=True, help_text='Номер инцидента/заявки в ITIL системе', max_length=100, null=True, verbose_name='Номер ITIL'),
        ),
    ]
