# Generated by Django 4.2 on 2025-10-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_task_itil_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'К выполнению'), ('in_progress', 'В работе'), ('waiting', 'Ожидание'), ('checking', 'Проверка'), ('done', 'Выполнено')], default='todo', max_length=20, verbose_name='Статус'),
        ),
    ]
