# Generated by Django 4.2 on 2025-10-17 00:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0015_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='additional_assignees',
            field=models.ManyToManyField(blank=True, related_name='additional_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Дополнительные исполнители'),
        ),
    ]
