# Generated by Django 4.2 on 2025-10-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_task_additional_assignees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'К выполнению'), ('waiting', 'Ожидание'), ('checking', 'Проверка'), ('done', 'Выполнено')], default='todo', max_length=20, verbose_name='Статус'),
        ),
    ]
