# Generated by Django 4.2 on 2025-10-23 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_task_closed_at'),
    ]

    operations = [
    ]
