# Generated by Django 4.2 on 2025-10-30 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0019_add_oes_object_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название актива')),
                ('asset_type', models.CharField(help_text='Например: Техника, Оборудование, Транспорт', max_length=100, verbose_name='Тип актива')),
                ('model', models.CharField(blank=True, max_length=255, verbose_name='Модель')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Актив (ручной ввод)',
                'verbose_name_plural': 'Активы (ручной ввод)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RadioType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('sn', models.CharField(max_length=100, unique=True, verbose_name='Серийный номер')),
                ('ccid', models.CharField(blank=True, max_length=100, verbose_name='CCID')),
                ('sim', models.CharField(blank=True, max_length=50, verbose_name='SIM')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Рация',
                'verbose_name_plural': 'Рации',
                'ordering': ['model', 'sn'],
            },
        ),
        migrations.CreateModel(
            name='RadioRepair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repair_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата ремонта')),
                ('description', models.TextField(verbose_name='Описание работ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repairs', to='tasks.radiotype', verbose_name='Рация')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='radio_repairs', to=settings.AUTH_USER_MODEL, verbose_name='Выполнил')),
            ],
            options={
                'verbose_name': 'Ремонт рации',
                'verbose_name_plural': 'Ремонты раций',
                'ordering': ['-repair_date'],
            },
        ),
        migrations.CreateModel(
            name='RadioAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255, verbose_name='Подразделение')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата возврата')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radio_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Выдано кому')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tasks.radiotype', verbose_name='Рация')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_radios', to=settings.AUTH_USER_MODEL, verbose_name='Выдал')),
            ],
            options={
                'verbose_name': 'Выдача рации',
                'verbose_name_plural': 'Выдачи раций',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='manual_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.manualasset', verbose_name='Ручной актив'),
        ),
    ]
