# Generated by Django 4.2 on 2025-10-30 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_manualasset_radiotype_radiorepair_radioassignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radioassignment',
            name='assignee',
        ),
        migrations.AddField(
            model_name='radioassignment',
            name='assignee_name',
            field=models.CharField(default='', max_length=255, verbose_name='Выдано кому'),
        ),
    ]
