# Generated by Django 4.2 on 2025-10-30 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_remove_radioassignment_assignee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiotype',
            name='ccid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='CCID'),
        ),
        migrations.AlterField(
            model_name='radiotype',
            name='sim',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID'),
        ),
    ]
