# Generated by Django 4.2 on 2025-10-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_alter_radiotype_ccid_alter_radiotype_sim'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='radioassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('returned_at__isnull', True)), fields=('device',), name='unique_open_assignment_per_device'),
        ),
    ]
