# Generated by Django 4.2 on 2025-10-30 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_radioassignment_unique_open_assignment_per_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название модели')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Модель рации',
                'verbose_name_plural': 'Модели раций',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='radiotype',
            options={'ordering': ['model__name', 'sn'], 'verbose_name': 'Рация', 'verbose_name_plural': 'Рации'},
        ),
        migrations.AlterField(
            model_name='radiotype',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='radios', to='tasks.radiomodel', verbose_name='Модель'),
        ),
    ]
