# Generated by Django 4.2 on 2025-10-31 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_radiomodel_alter_radiotype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radioassignment',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='radio_assignments/', verbose_name='PDF файл'),
        ),
    ]
