# Generated by Django 4.2 on 2026-02-25 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_radioassignment_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdleRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.IntegerField(help_text='Уникальный ID записи из внешнего API', unique=True, verbose_name='ID простоя из API')),
                ('object_uuid', models.UUIDField(blank=True, db_index=True, help_text='object_uuid из API для связки с OesObject.mdm_object_uuid', null=True, verbose_name='UUID объекта')),
                ('object_id_external', models.IntegerField(blank=True, help_text='object_id из API', null=True, verbose_name='ID объекта из API')),
                ('begin_dt', models.DateTimeField(verbose_name='Начало простоя')),
                ('end_dt', models.DateTimeField(blank=True, null=True, verbose_name='Конец простоя')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Длительность (мин)')),
                ('duration_from_shift', models.IntegerField(blank=True, null=True, verbose_name='Длительность от смены (мин)')),
                ('idle_type_id', models.IntegerField(blank=True, null=True, verbose_name='ID типа простоя')),
                ('idle_type_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Тип простоя')),
                ('category_id', models.IntegerField(blank=True, null=True, verbose_name='ID категории простоя')),
                ('category_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Категория простоя')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('selected', models.BooleanField(default=False, verbose_name='Выбран')),
                ('is_manual', models.BooleanField(default=False, verbose_name='Ручной ввод')),
                ('is_engine_on', models.BooleanField(default=False, verbose_name='Двигатель включён')),
                ('is_allowed_zone', models.BooleanField(default=False, verbose_name='В разрешённой зоне')),
                ('lat', models.CharField(blank=True, default='', max_length=50, verbose_name='Широта')),
                ('lon', models.CharField(blank=True, default='', max_length=50, verbose_name='Долгота')),
                ('geozones', models.CharField(blank=True, default='', max_length=500, verbose_name='Геозоны')),
                ('updated_by', models.CharField(blank=True, default='', max_length=255, verbose_name='Обновлено кем')),
                ('enterprise_id', models.IntegerField(blank=True, null=True, verbose_name='ID предприятия')),
                ('raw_data', models.JSONField(blank=True, null=True, verbose_name='Сырые данные из API')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('shift_type', models.CharField(blank=True, choices=[('day', 'Дневная'), ('night', 'Ночная')], default='', max_length=10, verbose_name='Тип смены')),
                ('oes_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idle_records', to='tasks.oesobject', verbose_name='Объект OES')),
            ],
            options={
                'verbose_name': 'Простой техники',
                'verbose_name_plural': 'Простои техники',
                'ordering': ['-begin_dt'],
            },
        ),
        migrations.AddIndex(
            model_name='idlerecord',
            index=models.Index(fields=['begin_dt', 'end_dt'], name='tasks_idler_begin_d_5837e0_idx'),
        ),
        migrations.AddIndex(
            model_name='idlerecord',
            index=models.Index(fields=['object_uuid'], name='tasks_idler_object__8f1ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='idlerecord',
            index=models.Index(fields=['category_name'], name='tasks_idler_categor_c565be_idx'),
        ),
    ]
