# Generated by Django 4.2 on 2026-02-25 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0026_idlerecord_idlerecord_tasks_idler_begin_d_5837e0_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTagConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clickhouse_table', models.CharField(choices=[('trucks', 'Самосвалы (telemetry.trucks)'), ('heavy_equipment', 'Тяжёлая техника (telemetry.heavy_equipment)')], max_length=50, verbose_name='Таблица ClickHouse')),
                ('tag_name', models.CharField(help_text='Например: lon, lat, temp_engine, dut, speed_gps', max_length=100, verbose_name='Имя тега (колонка в ClickHouse)')),
                ('check_type', models.CharField(choices=[('exists', 'Наличие данных (значение ≠ -1000000)'), ('threshold_min', 'Минимальный порог (значение ≥ min)'), ('threshold_max', 'Максимальный порог (значение ≤ max)'), ('threshold_range', 'Диапазон (min ≤ значение ≤ max)'), ('change', 'Изменение (значение должно меняться)')], default='exists', max_length=20, verbose_name='Тип проверки')),
                ('threshold_min', models.FloatField(blank=True, help_text='Для threshold_min и threshold_range', null=True, verbose_name='Минимальный порог')),
                ('threshold_max', models.FloatField(blank=True, help_text='Для threshold_max и threshold_range', null=True, verbose_name='Максимальный порог')),
                ('min_change', models.FloatField(blank=True, help_text="Для типа 'Изменение': разница между max и min за период. Например 0.0001 для GPS координат.", null=True, verbose_name='Минимальная дельта изменения')),
                ('description', models.CharField(blank=True, default='', help_text="Что проверяем и зачем. Например: 'GPS координаты должны меняться при работе'", max_length=500, verbose_name='Описание проверки')),
                ('task_priority', models.CharField(choices=[('critical', 'Критический'), ('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], default='medium', help_text='Приоритет задачи, которая будет создана при провале проверки', max_length=20, verbose_name='Приоритет задачи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('oes_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_configs', to='tasks.oesmodel', verbose_name='Модель техники')),
            ],
            options={
                'verbose_name': 'Конфигурация тега мониторинга',
                'verbose_name_plural': 'Конфигурации тегов мониторинга',
                'ordering': ['oes_model', 'tag_name'],
                'unique_together': {('oes_model', 'tag_name')},
            },
        ),
    ]
