# Generated by Django 4.2 on 2026-02-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_modeltagconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='oesobject',
            name='exclude_from_monitoring',
            field=models.BooleanField(default=False, help_text='Консервация, списание, ремонт — не проверять телеметрию', verbose_name='Исключить из мониторинга'),
        ),
        migrations.AddField(
            model_name='oesobject',
            name='exclude_reason',
            field=models.CharField(blank=True, default='', help_text='Например: Консервация, Списан, В ремонте', max_length=100, verbose_name='Причина исключения'),
        ),
    ]
