# Generated by Django 4.2 on 2026-02-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_oesobject_exclude_from_monitoring_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modeltagconfig',
            options={'ordering': ['tag_name'], 'verbose_name': 'Конфигурация тега мониторинга', 'verbose_name_plural': 'Конфигурации тегов мониторинга'},
        ),
        migrations.AlterUniqueTogether(
            name='modeltagconfig',
            unique_together={('tag_name', 'clickhouse_table')},
        ),
        migrations.AddField(
            model_name='modeltagconfig',
            name='oes_models',
            field=models.ManyToManyField(related_name='tag_configs', to='tasks.oesmodel', verbose_name='Модели техники'),
        ),
        migrations.RemoveField(
            model_name='modeltagconfig',
            name='oes_model',
        ),
    ]
