# Generated by Django 4.2 on 2026-02-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_alter_modeltagconfig_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringGeozone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Например: База, Ремзона, Парковка', max_length=255, verbose_name='Название')),
                ('lat', models.FloatField(help_text='Например: 46.958700', verbose_name='Широта центра')),
                ('lon', models.FloatField(help_text='Например: 142.738300', verbose_name='Долгота центра')),
                ('radius_m', models.PositiveIntegerField(default=500, verbose_name='Радиус (метры)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Геозона мониторинга',
                'verbose_name_plural': 'Геозоны мониторинга',
                'ordering': ['name'],
            },
        ),
    ]
